# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CommonSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommonSDK
  pod 'Purchasely' 
  pod 'FirebaseAnalytics'
  pod 'Firebase'
  pod 'Mixpanel-swift'
  pod 'FBSDKCoreKit'


end
